#include <pthread.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <sched.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <tgmath.h>
#include <float.h>
#include <signal.h>
#include <dirent.h>
#include <grp.h>
#include <ctype.h>
#include <wctype.h>
#include <wchar.h>
#include <errno.h>
#include <locale.h>
#include <malloc.h>
#include <sys/wait.h>
#include <sys/reent.h>
#include <signal.h>
#include <time.h>
#include <sys/times.h>

#include "semaphore.h"
#include "mqueue.h"
#include "aio.h"
#include "caos.h"
#include "hwpl/sys.h"
#include "hwdl/sys.h"
#include "hwpl/core.h"
#include "hwpl/adc.h"
#include "hwpl/dac.h"
#include "hwpl/mem.h"
#include "hwpl/spi.h"
#include "hwpl/uart.h"
#include "hwpl/usb.h"
#include "hwpl/i2c.h"
#include "hwpl/pwm.h"
#include "hwpl/rtc.h"
#include "hwpl/eint.h"
#include "hwpl/pio.h"
#include "hwpl/qei.h"
#include "hwpl/tmr.h"
#include "hwpl/task.h"

#include "libgcc.h"

#ifndef USE_STDIO
#define USE_STDIO 1
#endif

#ifndef USE_FLOAT
#define USE_FLOAT 1
#endif

#ifndef USE_PTHREAD
#define USE_PTHREAD 1
#endif

#ifndef USE_SEMAPHORE
#define USE_SEMAPHORE 1
#endif

#ifndef USE_SCHED
#define USE_SCHED 1
#endif

#ifndef USE_AIO
#define USE_AIO 1
#endif

#ifndef USE_MQUEUE
#define USE_MQUEUE 1
#endif

#ifndef USE_SIGNAL
#define USE_SIGNAL 1
#endif

#ifndef USE_GRP
#define USE_GRP 1
#endif

#define FLOAT_FLAG (USE_FLOAT<<16)
#define AIO_FLAG (USE_AIO<<17)
#define MQUEUE_FLAG (USE_MQUEUE<<18)
#define GRP_FLAG (USE_GRP<<19)
#define SCHED_FLAG (USE_SCHED<<20)
#define SEMAPHORE_FLAG (USE_SEMAPHORE<<21)
#define SIGNAL_FLAG (USE_SIGNAL<<22)

void __cxa_pure_virtual(void){}
char __aeabi_unwind_cpp_pr0[0];

void __div0(void){
	while(1){}
}

extern void crt_load_data(void * global_impure, void * code_start, int code_size, int data_size);
extern char ** const crt_import_argv(int argc, char * const argv[]);

uint32_t const symbols_table[] = {
		//The first position is the signature
		(uint32_t)0x00000132,
		(uint32_t)__cxa_pure_virtual,
		(uint32_t)__get_PSP,
		(uint32_t)__set_PSP,
		(uint32_t)__get_MSP,
		(uint32_t)__set_MSP,
		(uint32_t)__get_BASEPRI,
		(uint32_t)__set_BASEPRI,
		(uint32_t)__get_PRIMASK,
		(uint32_t)__set_PRIMASK,
		(uint32_t)__get_FAULTMASK,
		(uint32_t)__set_FAULTMASK,
		(uint32_t)__get_CONTROL,
		(uint32_t)__set_CONTROL,
		(uint32_t)__REV,
		(uint32_t)__REV16,
		(uint32_t)__REVSH,
		(uint32_t)__RBIT,
		(uint32_t)__LDREXB,
		(uint32_t)__LDREXH,
		(uint32_t)__LDREXW,
		(uint32_t)__STREXB,
		(uint32_t)__STREXH,
		(uint32_t)__STREXW,
		(uint32_t)hwpl_core_privcall,
		(uint32_t)hwpl_adc_ioctl,
		(uint32_t)hwpl_core_ioctl,
		(uint32_t)hwpl_dac_ioctl,
		(uint32_t)hwpl_eint_ioctl,
		(uint32_t)hwpl_mem_read,
		(uint32_t)hwpl_i2c_ioctl,
		(uint32_t)hwpl_pio_ioctl,
		//(uint32_t)hwpl_pwm_ioctl,
		(uint32_t)hwpl_tmr_ioctl,
		//(uint32_t)hwpl_qei_ioctl,
		(uint32_t)hwpl_tmr_ioctl,
		(uint32_t)hwpl_rtc_ioctl,
		//(uint32_t)hwpl_spi_ioctl,
		(uint32_t)hwpl_tmr_ioctl,
		(uint32_t)hwpl_tmr_ioctl,
		(uint32_t)hwpl_uart_ioctl,
		(uint32_t)hwpl_usb_ioctl,
		(uint32_t)task_priv_set_stackguard,
		(uint32_t)realloc,
		(uint32_t)&_global_impure_ptr,
		(uint32_t)&_impure_ptr,
		(uint32_t)&__sf_fake_stdin,
		(uint32_t)&__sf_fake_stdout,
		(uint32_t)&__sf_fake_stderr,
		(uint32_t)__aeabi_uidiv,
		(uint32_t)__aeabi_uidivmod,
		(uint32_t)__aeabi_idiv,
		(uint32_t)__aeabi_idivmod,
		(uint32_t)__umodsi3,
		(uint32_t)__modsi3,
		(uint32_t)__div0,
		(uint32_t)__aeabi_llsr,
		(uint32_t)__aeabi_lasr,
		(uint32_t)__aeabi_llsl,
		(uint32_t)__clzsi2,
		(uint32_t)__clzdi2,
		(uint32_t)__muldi3,
		(uint32_t)__negdi2,
		(uint32_t)__cmpdi2,
		(uint32_t)__ucmpdi2,
		(uint32_t)__absvsi2,
		(uint32_t)__absvdi2,
		(uint32_t)__addvsi3,
		(uint32_t)__addvdi3,
		(uint32_t)__subvsi3,
		(uint32_t)__subvdi3,
		(uint32_t)__mulvsi3,
		(uint32_t)__mulvdi3,
		(uint32_t)__negvsi2,
		(uint32_t)__negvdi2,
		(uint32_t)__ffsdi2,
		(uint32_t)__popcountsi2,
		(uint32_t)__popcountdi2,
		(uint32_t)__paritysi2,
		(uint32_t)__paritydi2,
		(uint32_t)__mulsc3,
		(uint32_t)__muldc3,
		(uint32_t)__divsc3,
		(uint32_t)__divdc3,
		(uint32_t)__bswapsi2,
		(uint32_t)__bswapdi2,
		(uint32_t)__divdi3,
		(uint32_t)__moddi3,
		(uint32_t)__udivdi3,
		(uint32_t)__umoddi3,
		(uint32_t)abort,
		(uint32_t)asctime,
		(uint32_t)asctime_r,
		(uint32_t)exit,
		(uint32_t)atexit,
		(uint32_t)atoi,
		(uint32_t)atol,
		(uint32_t)bsearch,
		(uint32_t)clearerr,
		(uint32_t)clock,
		(uint32_t)ctime,
		(uint32_t)difftime,
		(uint32_t)div,
		(uint32_t)__errno,
		(uint32_t)fclose,
		(uint32_t)feof,
		(uint32_t)ferror,
		(uint32_t)fflush,
		(uint32_t)fgetc,
		(uint32_t)fgetpos,
		(uint32_t)fgets,
		(uint32_t)fileno,
		(uint32_t)fopen,
		(uint32_t)fputc,
		(uint32_t)fputs,
		(uint32_t)fread,
		(uint32_t)freopen,
		(uint32_t)fscanf,
		(uint32_t)fseek,
		(uint32_t)fsetpos,
		(uint32_t)ftell,
		(uint32_t)fwrite,
		(uint32_t)getc,
		(uint32_t)getchar,
		(uint32_t)getenv,
		(uint32_t)gets,
		(uint32_t)gmtime,
		(uint32_t)gmtime_r,
		(uint32_t)iswalnum,
		(uint32_t)iswalpha,
		(uint32_t)iswblank,
		(uint32_t)iswcntrl,
		(uint32_t)iswctype,
		(uint32_t)iswdigit,
		(uint32_t)iswgraph,
		(uint32_t)iswlower,
		(uint32_t)iswprint,
		(uint32_t)iswpunct,
		(uint32_t)iswspace,
		(uint32_t)iswupper,
		(uint32_t)iswxdigit,
		(uint32_t)labs,
		(uint32_t)localtime,
		(uint32_t)localtime_r,
		(uint32_t)ldiv,
		(uint32_t)lldiv,
		(uint32_t)mblen,
		(uint32_t)mbstowcs,
		(uint32_t)mbtowc,
		(uint32_t)memchr,
		(uint32_t)memcmp,
		(uint32_t)memcpy,
		(uint32_t)memmove,
		(uint32_t)memset,
		(uint32_t)mktime,
		(uint32_t)perror,
		(uint32_t)putc,
		(uint32_t)putchar,
		(uint32_t)puts,
		(uint32_t)qsort,
		(uint32_t)raise,
		(uint32_t)srand,
		(uint32_t)rand,
		(uint32_t)remove,
		(uint32_t)rename,
		(uint32_t)rewind,
		(uint32_t)scanf,
		(uint32_t)setbuf,
		(uint32_t)setvbuf,
		(uint32_t)sscanf,
		(uint32_t)strcat,
		(uint32_t)strchr,
		(uint32_t)strcmp,
		(uint32_t)strcoll,
		(uint32_t)strcpy,
		(uint32_t)strcspn,
		(uint32_t)strerror,
		(uint32_t)strftime,
		(uint32_t)strlen,
		(uint32_t)strncat,
		(uint32_t)strncmp,
		(uint32_t)strncpy,
		(uint32_t)strnlen,
		(uint32_t)strpbrk,
		(uint32_t)strptime,
		(uint32_t)strrchr,
		(uint32_t)strspn,
		(uint32_t)strstr,
		(uint32_t)strtod,
		(uint32_t)strtof,
		(uint32_t)strtok,
		(uint32_t)strtok_r,
		(uint32_t)strtol,
		(uint32_t)strtoll,
		(uint32_t)strtoul,
		(uint32_t)strtoull,
		(uint32_t)strxfrm,
		(uint32_t)close,
		(uint32_t)execve,
		(uint32_t)fcntl,
		(uint32_t)fstat,
		(uint32_t)getpid,
		(uint32_t)gettimeofday,
		(uint32_t)kill,
		(uint32_t)link,
		(uint32_t)lseek,
		(uint32_t)open,
		(uint32_t)read,
		(uint32_t)stat,
		(uint32_t)system,
		(uint32_t)times,
		(uint32_t)unlink,
		(uint32_t)wait,
		(uint32_t)write,
		(uint32_t)time,
		(uint32_t)towctrans,
		(uint32_t)towlower,
		(uint32_t)towupper,
		(uint32_t)ungetc,
		(uint32_t)vfscanf,
		(uint32_t)vscanf,
		(uint32_t)vsscanf,
		(uint32_t)wcscasecmp,
		(uint32_t)wcscmp,
		(uint32_t)wcsncasecmp,
		(uint32_t)wcsncmp,
		(uint32_t)wcstombs,
		(uint32_t)wctomb,
		(uint32_t)wctrans,
		(uint32_t)wctype,
		(uint32_t)fputwc,
		(uint32_t)setlocale,
		(uint32_t)localeconv,
		(uint32_t)mbrtowc,
		(uint32_t)nanf,
		(uint32_t)strncasecmp,
		(uint32_t)wcrtomb,
		(uint32_t)sys_ioctl,
		(uint32_t)aio_cancel,
		(uint32_t)aio_error,
		(uint32_t)aio_fsync,
		(uint32_t)aio_read,
		(uint32_t)aio_write,
		(uint32_t)aio_return,
		(uint32_t)aio_suspend,
		(uint32_t)lio_listio,
		(uint32_t)mkfs,
		(uint32_t)sched_get_priority_max,
		(uint32_t)sched_get_priority_min,
		(uint32_t)sched_getparam,
		(uint32_t)sched_getscheduler,
		(uint32_t)sched_rr_get_interval,
		(uint32_t)sched_setparam,
		(uint32_t)sched_setscheduler,
		(uint32_t)sched_yield,
		(uint32_t)access,
		(uint32_t)ioctl,
		(uint32_t)mkdir,
		(uint32_t)rmdir,
		(uint32_t)sleep,
		(uint32_t)usleep,
		(uint32_t)chmod,
		(uint32_t)mallinfo,
		(uint32_t)malloc,
		(uint32_t)free,
		(uint32_t)calloc,
		(uint32_t)_malloc_r,
		(uint32_t)_free_r,
		(uint32_t)clock_getcpuclockid,
		(uint32_t)clock_gettime,
		(uint32_t)clock_getres,
		(uint32_t)clock_settime,
		(uint32_t)hibernate,
		(uint32_t)powerdown,
		(uint32_t)pthread_create,
		(uint32_t)pthread_join,
		(uint32_t)pthread_getschedparam,
		(uint32_t)pthread_setschedparam,
		(uint32_t)pthread_cancel,
		(uint32_t)pthread_cond_init,
		(uint32_t)pthread_cond_destroy,
		(uint32_t)pthread_cond_broadcast,
		(uint32_t)pthread_cond_signal,
		(uint32_t)pthread_cond_wait,
		(uint32_t)pthread_cond_timedwait,
		(uint32_t)pthread_condattr_init,
		(uint32_t)pthread_condattr_destroy,
		(uint32_t)pthread_condattr_getpshared,
		(uint32_t)pthread_condattr_setpshared,
		(uint32_t)pthread_condattr_getclock,
		(uint32_t)pthread_condattr_setclock,
		(uint32_t)pthread_attr_getdetachstate,
		(uint32_t)pthread_attr_setdetachstate,
		(uint32_t)pthread_attr_getguardsize,
		(uint32_t)pthread_attr_setguardsize,
		(uint32_t)pthread_attr_getinheritsched,
		(uint32_t)pthread_attr_setinheritsched,
		(uint32_t)pthread_attr_getschedparam,
		(uint32_t)pthread_attr_setschedparam,
		(uint32_t)pthread_attr_getschedpolicy,
		(uint32_t)pthread_attr_setschedpolicy,
		(uint32_t)pthread_attr_getscope,
		(uint32_t)pthread_attr_setscope,
		(uint32_t)pthread_attr_getstacksize,
		(uint32_t)pthread_attr_setstacksize,
		(uint32_t)pthread_attr_getstackaddr,
		(uint32_t)pthread_attr_setstackaddr,
		(uint32_t)pthread_attr_init,
		(uint32_t)pthread_attr_destroy,
		(uint32_t)pthread_mutexattr_getprioceiling,
		(uint32_t)pthread_mutexattr_setprioceiling,
		(uint32_t)pthread_mutexattr_getprotocol,
		(uint32_t)pthread_mutexattr_setprotocol,
		(uint32_t)pthread_mutexattr_getpshared,
		(uint32_t)pthread_mutexattr_setpshared,
		(uint32_t)pthread_mutexattr_gettype,
		(uint32_t)pthread_mutexattr_settype,
		(uint32_t)pthread_mutexattr_init,
		(uint32_t)pthread_mutexattr_destroy,
		(uint32_t)pthread_mutex_init,
		(uint32_t)pthread_mutex_lock,
		(uint32_t)pthread_mutex_trylock,
		(uint32_t)pthread_mutex_unlock,
		(uint32_t)pthread_mutex_destroy,
		(uint32_t)pthread_mutex_getprioceiling,
		(uint32_t)pthread_mutex_setprioceiling,
		(uint32_t)pthread_self,
		(uint32_t)signal,
		(uint32_t)sigaction,
		(uint32_t)pthread_sigmask,
		(uint32_t)sigprocmask,
		(uint32_t)sigpending,
		(uint32_t)sigsuspend,
		(uint32_t)pthread_kill,
		(uint32_t)sigqueue,
		(uint32_t)sigwait,
		(uint32_t)sigtimedwait,
		(uint32_t)sigwaitinfo,
		(uint32_t)sigaddset,
		(uint32_t)sigdelset,
		(uint32_t)sigismember,
		(uint32_t)sigfillset,
		(uint32_t)sigemptyset,
		(uint32_t)waitpid,
		(uint32_t)_wait,
		(uint32_t)sem_init,
		(uint32_t)sem_destroy,
		(uint32_t)sem_getvalue,
		(uint32_t)sem_open,
		(uint32_t)sem_post,
		(uint32_t)sem_timedwait,
		(uint32_t)sem_trywait,
		(uint32_t)sem_unlink,
		(uint32_t)sem_close,
		(uint32_t)sem_wait,
		(uint32_t)mq_getattr,
		(uint32_t)mq_setattr,
		(uint32_t)mq_open,
		(uint32_t)mq_close,
		(uint32_t)mq_unlink,
		(uint32_t)mq_notify,
		(uint32_t)mq_timedreceive,
		(uint32_t)mq_receive,
		(uint32_t)mq_timedsend,
		(uint32_t)mq_send,
		(uint32_t)_exit,
		(uint32_t)chown,
		(uint32_t)closedir,
		(uint32_t)opendir,
		(uint32_t)readdir_r,
		(uint32_t)readdir,
		(uint32_t)rewinddir,
		(uint32_t)seekdir,
		(uint32_t)telldir,
#if USE_FLOAT == 1
		(uint32_t)fprintf,
		(uint32_t)printf,
		(uint32_t)snprintf,
		(uint32_t)vfprintf,
		(uint32_t)sprintf,
		(uint32_t)vprintf,
		(uint32_t)vsnprintf,
		(uint32_t)vsprintf,
		(uint32_t)asinh,
		(uint32_t)atan,
		(uint32_t)cbrt,
		(uint32_t)ceil,
		(uint32_t)copysign,
		(uint32_t)cos,
		(uint32_t)erf,
		(uint32_t)erfc,
		(uint32_t)fabs,
		(uint32_t)fdim,
		(uint32_t)floor,
		(uint32_t)fma,
		(uint32_t)fmax,
		(uint32_t)fmin,
		(uint32_t)frexp,
		(uint32_t)ilogb,
		(uint32_t)ldexp,
		(uint32_t)llrint,
		(uint32_t)llround,
		(uint32_t)log1p,
		(uint32_t)log2,
		(uint32_t)logb,
		(uint32_t)lround,
		(uint32_t)modf,
		(uint32_t)nan,
		(uint32_t)nearbyint,
		(uint32_t)nextafter,
		(uint32_t)remquo,
		(uint32_t)rint,
		(uint32_t)round,
		(uint32_t)scalbln,
		(uint32_t)scalbn,
		(uint32_t)sin,
		(uint32_t)tan,
		(uint32_t)tanh,
		(uint32_t)trunc,
		(uint32_t)acos,
		(uint32_t)acosh,
		(uint32_t)asin,
		(uint32_t)atan2,
		(uint32_t)atanh,
		(uint32_t)cosh,
		(uint32_t)exp,
		(uint32_t)exp2,
		(uint32_t)fmod,
		(uint32_t)hypot,
		(uint32_t)lgamma,
		(uint32_t)log,
		(uint32_t)log10,
		(uint32_t)pow,
		(uint32_t)remainder,
		(uint32_t)sinh,
		(uint32_t)sqrt,
		(uint32_t)tgamma,
		(uint32_t)expm1,
		(uint32_t)finite,
		(uint32_t)matherr,
		(uint32_t)abs,
		(uint32_t)atof,
		(uint32_t)__aeabi_fneg,
		//alias:.global __negsf2; __negsf2 = __aeabi_fneg;
		(uint32_t)__aeabi_fsub,
		//alias:.global __subsf3; __subsf3 = __aeabi_fsub;
		(uint32_t)__aeabi_fadd,
		//alias:.global __addsf3; __addsf3 = __aeabi_fadd;
		(uint32_t)__aeabi_ui2f,
		//alias:.global __floatunsisf; __floatunsisf = __aeabi_ui2f;
		(uint32_t)__aeabi_i2f,
		//alias:.global __floatsisf; __floatsisf = __aeabi_i2f;
		(uint32_t)__aeabi_ul2f,
		//alias:.global __floatundisf; __floatundisf = __aeabi_ul2f;
		(uint32_t)__aeabi_l2f,
		//alias:.global __floatdisf; __floatdisf = __aeabi_l2f;
		(uint32_t)__aeabi_fmul,
		//alias:.global __mulsf3; __mulsf3 = __aeabi_fmul;
		(uint32_t)__aeabi_fdiv,
		//alias:.global __divsf3; __divsf3 = __aeabi_fdiv;
		(uint32_t)__aeabi_fcmpun,
		//alias:.global __unordsf2; __unordsf2 = __aeabi_fcmpun;
		(uint32_t)__aeabi_f2iz,
		//alias:.global __fixsfsi; __fixsfsi = __aeabi_f2iz;
		(uint32_t)__aeabi_f2uiz,
		//alias:.global __fixunssfsi; __fixunssfsi = __aeabi_f2uiz;
		(uint32_t)__aeabi_f2lz,
		//alias:.global __fixsfdi; __fixsfdi = __aeabi_f2lz;
		(uint32_t)__aeabi_f2ulz,
		//alias:.global __fixunssfdi; __fixunssfdi = __aeabi_f2ulz;
		(uint32_t)__aeabi_l2f,
		//alias:.global __floatdisf; __floatdisf = __aeabi_l2f;
		(uint32_t)__aeabi_frsub,
		(uint32_t)__gesf2,
		//alias:.global __gtsf2; __gtsf2 = __gesf2;
		(uint32_t)__lesf2,
		//alias:.global __ltsf2; __ltsf2 = __lesf2;
		(uint32_t)__cmpsf2,
		//alias:.global __nesf2; __nesf2 = __cmpsf2;
		//alias:.global __eqsf2; __eqsf2 = __cmpsf2;
		(uint32_t)__aeabi_cfrcmple,
		(uint32_t)__aeabi_cfcmpeq,
		(uint32_t)__aeabi_fcmpeq,
		(uint32_t)__aeabi_fcmplt,
		(uint32_t)__aeabi_fcmple,
		(uint32_t)__aeabi_fcmpge,
		(uint32_t)__aeabi_fcmpgt,
		(uint32_t)__powisf2,
		(uint32_t)__aeabi_dneg,
		//alias:.global __negdf2; __negdf2 = __aeabi_dneg;
		(uint32_t)__aeabi_dsub,
		//alias:.global __subdf3; __subdf3 = __aeabi_dsub;
		(uint32_t)__aeabi_dadd,
		//alias:.global __adddf3; __adddf3 = __aeabi_dadd;
		(uint32_t)__aeabi_ui2d,
		//alias:.global __floatunsidf; __floatunsidf = __aeabi_ui2d;
		(uint32_t)__aeabi_i2d,
		//alias:.global __floatsidf; __floatsidf = __aeabi_i2d;
		(uint32_t)__aeabi_f2d,
		//alias:.global __extendsfdf2; __extendsfdf2 = __aeabi_f2d;
		(uint32_t)__aeabi_d2f,
		//alias:.global __truncdfsf2; __truncdfsf2 = __aeabi_d2f;
		(uint32_t)__aeabi_ul2d,
		//alias:.global __floatundidf; __floatundidf = __aeabi_ul2d;
		(uint32_t)__aeabi_l2d,
		//alias:.global __floatdidf; __floatdidf = __aeabi_l2d;
		(uint32_t)__aeabi_dmul,
		//alias:.global __muldf3; __muldf3 = __aeabi_dmul;
		(uint32_t)__aeabi_ddiv,
		//alias:.global __divdf3; __divdf3 = __aeabi_ddiv;
		(uint32_t)__aeabi_dcmpun,
		//alias:.global __unorddf2; __unorddf2 = __aeabi_dcmpun;
		(uint32_t)__aeabi_d2iz,
		//alias:.global __fixdfsi; __fixdfsi = __aeabi_d2iz;
		(uint32_t)__aeabi_d2uiz,
		//alias:.global __fixunsdfsi; __fixunsdfsi = __aeabi_d2uiz;
		(uint32_t)__aeabi_d2lz,
		//alias:.global __fixdfdi; __fixdfdi = __aeabi_d2lz;
		(uint32_t)__aeabi_d2lz,
		//alias:.global __fixdfdi; __fixdfdi = __aeabi_d2lz;
		(uint32_t)__aeabi_d2ulz,
		//alias:.global __fixunsdfdi; __fixunsdfdi = __aeabi_d2ulz;
		(uint32_t)__aeabi_l2d,
		//alias:.global __floatdidf; __floatdidf = __aeabi_l2d;
		(uint32_t)__gnu_h2f_ieee,
		//alias:.global __extendhfsf2; __extendhfsf2 = __gnu_h2f_ieee;
		(uint32_t)__gnu_f2h_ieee,
		//alias:.global __truncsfhf2; __truncsfhf2 = __gnu_f2h_ieee;
		(uint32_t)__aeabi_drsub,
		(uint32_t)__gedf2,
		//alias:.global __gtdf2; __gtdf2 = __gedf2;
		(uint32_t)__ledf2,
		//alias:.global __ltdf2; __ltdf2 = __ledf2;
		(uint32_t)__cmpdf2,
		//alias:.global __nedf2; __nedf2 = __cmpdf2;
		//alias:.global __eqdf2; __eqdf2 = __cmpdf2;
		(uint32_t)__aeabi_cdrcmple,
		(uint32_t)__aeabi_cdcmpeq,
		(uint32_t)__aeabi_dcmpeq,
		(uint32_t)__aeabi_dcmplt,
		(uint32_t)__aeabi_dcmple,
		(uint32_t)__aeabi_dcmpge,
		(uint32_t)__aeabi_dcmpgt,
		(uint32_t)__powidf2,
#else
		(unsigned int)fiprintf,
		(unsigned int)iprintf,
		(unsigned int)sniprintf,
		(unsigned int)vfiprintf,
		(unsigned int)siprintf,
		(unsigned int)viprintf,
		(unsigned int)vsniprintf,
		(unsigned int)vsiprintf, // This needs to have the rest of the float functions defined as 0 -- installer won't install the program
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
#endif
		(uint32_t)signal_callback,
		(uint32_t)__sinit,
		(uint32_t)task_setstackguard,
		(uint32_t)crt_import_argv,
		(uint32_t)crt_load_data,
		0
};
