/*! \file */

#ifndef CONFIG_H_
#define CONFIG_H_

/*! \addtogroup CAOS
 * @{
 */

/*! \brief Version \showinitializer */
#define VERSION "1.3.2"
#define BCDVERSION 0x132

/*! @} */

#include <stdint.h>

#ifdef __lpc17xx
#define ARCH "lpc17xx"
#define CAOSLIB_USECOND_TMR_RESET_OC 0
#define CAOSLIB_USECOND_TMR_SLEEP_OC 1
#define CAOSLIB_USECOND_TMR_USBDFU_OC 3
#define PTHREAD_DEFAULT_STACK_SIZE 1536
#define MALLOC_CHUNK_SIZE 64
#define MALLOC_SBRK_JUMP_SIZE 128
#define SCHED_FIRST_THREAD_STACK_SIZE 2048
#define SCHED_DEFAULT_STACKGUARD_SIZE 32
#endif

#ifdef __lpc177x_8x
#define ARCH "lpc177x_8x"
#define CAOSLIB_USECOND_TMR_RESET_OC 0
#define CAOSLIB_USECOND_TMR_SLEEP_OC 1
#define CAOSLIB_USECOND_TMR_USBDFU_OC 3
#define PTHREAD_DEFAULT_STACK_SIZE 1536
#define MALLOC_CHUNK_SIZE 64
#define MALLOC_SBRK_JUMP_SIZE 128
#define SCHED_FIRST_THREAD_STACK_SIZE 2048
#define SCHED_DEFAULT_STACKGUARD_SIZE 32
#endif


#define PTHREAD_MAX_LOCKS 1024
#define PTHREAD_MUTEX_PRIO_CEILING 0
#define PTHREAD_STACK_MIN 128
#define SCHED_LOWEST_PRIORITY 0
#define SCHED_HIGHEST_PRIORITY 31
#define SCHED_DEFAULT_PRIORITY 0
#define SCHED_RR_DURATION 10

#define SINGLE_PROCESS 0
#define SINGLE_TASK 0
#define USE_FILESYSTEM 1
#define USE_MEMORY_PROTECTION 1
#define USE_STDIO 1

#define DEVICE_MAX_RAM 65536
#define DEVICE_SYS_RAM 4096
#define DEVICE_RAM_PAGE_SIZE 1024

#endif
