/* Copyright 2011; All Rights Reserved
 * Please see http://www.coactionos.com/license.html for
 * licensing information.
 */

#include "hwpl.h"
#include "hwpl/core.h"

__IO uint32_t *  _hwpl_get_iocon_regs(int port, int pin);

#define NUM_ENTRIES 8

typedef struct {
	uint16_t entry[NUM_ENTRIES];
} pinsel_table_t;

#define ENTRY(function, port) ((port<<8)|function)
#define ENTRY_GET_FUNCTION(entry) (entry & 0xFF)
#define ENTRY_GET_PORT(entry) ( (entry>>8) & 0xFF)

#define TOTAL_PINS (32*5+5)

const pinsel_table_t pinsel_func_table[TOTAL_PINS] = {
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_CAN, 1), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_I2C, 1), ENTRY(CORE_PERIPH_UART, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.0
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_CAN, 1), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_I2C, 1), ENTRY(CORE_PERIPH_UART, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.1
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 0), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.2
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 0), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.3
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_CAN, 2), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //0.4
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_CAN, 2), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //0.5
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //0.6
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_RESERVED, 2), ENTRY(CORE_PERIPH_RESERVED, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.7
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_RESERVED, 2), ENTRY(CORE_PERIPH_RESERVED, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.8
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.9
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 2), ENTRY(CORE_PERIPH_I2C, 2), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.10
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 2), ENTRY(CORE_PERIPH_I2C, 2), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.11
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_USB, 2), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.12
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_USB, 2), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.13
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_USB, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_USB, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.14
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.15
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.16
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.17
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.18
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_I2C, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.19
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_I2C, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.20
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_UART, 4), ENTRY(CORE_PERIPH_CAN, 1), ENTRY(CORE_PERIPH_UART, 4), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.21
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_UART, 4), ENTRY(CORE_PERIPH_CAN, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.22
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.23
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.24
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.25
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_DAC, 0), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.26
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_I2C, 0), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.27
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_I2C, 0), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.28
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_USB, 0), ENTRY(CORE_PERIPH_EINT, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.29
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_USB, 0), ENTRY(CORE_PERIPH_EINT, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.30
		{{ ENTRY(CORE_PERIPH_PIO, 0), ENTRY(CORE_PERIPH_USB, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.31

		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_SSP, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.0
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_SSP, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.1
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.2
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.3
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_SSP, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.4
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.5
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.6
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.7
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_SSP, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.8
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.9
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.10
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.11
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.12
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.13
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.14
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.15
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.16
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.17
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.18
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.19
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_QEI, 0), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.20
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.21
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.22
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_QEI, 0), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.23
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_QEI, 0), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.24
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_CLKOUT, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.25
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.26
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_CLKOUT, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.27
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.28
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_MCPWM, 0), ENTRY(CORE_PERIPH_UART, 4), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //1.29
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 2), ENTRY(CORE_PERIPH_USB, 0), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_I2C, 0), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.30
		{{ ENTRY(CORE_PERIPH_PIO, 1), ENTRY(CORE_PERIPH_USB, 2), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_ADC, 0), ENTRY(CORE_PERIPH_I2C, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.31

		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.0
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.1
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TRACE, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.2
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TRACE, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.3
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TRACE, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.4
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TRACE, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.5
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TRACE, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.6
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_CAN, 2), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.7
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_CAN, 2), ENTRY(CORE_PERIPH_UART, 2), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.8
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_USB, 1), ENTRY(CORE_PERIPH_UART, 2), ENTRY(CORE_PERIPH_UART, 4), ENTRY(CORE_PERIPH_ENET, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.9
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EINT, 0), ENTRY(CORE_PERIPH_NMI, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.10
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EINT, 1), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.11
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EINT, 2), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.12
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EINT, 3), ENTRY(CORE_PERIPH_SDC, 0), ENTRY(CORE_PERIPH_I2S, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //2.13
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_I2C, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.14
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_I2C, 1), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.15
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.16
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.17
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.18
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.19
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.20
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.21
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.22
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.23
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.24
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.25
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.26
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_SSP, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.27
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.28
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.29
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_I2C, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.30
		{{ ENTRY(CORE_PERIPH_PIO, 2), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_I2C, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.31

		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.0
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.1
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.2
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.3
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.4
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.5
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.6
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.7
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.8
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.9
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.10
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.11
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.12
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.13
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.14
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.15
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.16
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.17
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.18
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.19
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.20
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.21
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.22
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.23
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.24
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.25
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.26
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.27
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.28
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_PWM, 1), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.29
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_UART, 1), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.30
		{{ ENTRY(CORE_PERIPH_PIO, 3), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //3.31

		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.0
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.1
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.2
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.3
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.4
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.5
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.6
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.7
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.8
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.9
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.10
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.11
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.12
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.13
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.14
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.15
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.16
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.17
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.18
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.19
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_I2C, 2), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.20
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_I2C, 2), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.21
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_UART, 2), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.22
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_UART, 2), ENTRY(CORE_PERIPH_SSP, 1), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.23
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.24
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.25
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.26
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.27
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //4.28
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_UART, 3), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_I2C, 2), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0), ENTRY(CORE_PERIPH_LCD, 0) }}, //4.29
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.30
		{{ ENTRY(CORE_PERIPH_PIO, 4), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //4.31

		{{ ENTRY(CORE_PERIPH_PIO, 5), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //5.0
		{{ ENTRY(CORE_PERIPH_PIO, 5), ENTRY(CORE_PERIPH_EMC, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 2), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //5.1
		{{ ENTRY(CORE_PERIPH_PIO, 5), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_I2C, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //5.2
		{{ ENTRY(CORE_PERIPH_PIO, 5), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_UART, 4), ENTRY(CORE_PERIPH_I2C, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //5.3
		{{ ENTRY(CORE_PERIPH_PIO, 5), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_UART, 0), ENTRY(CORE_PERIPH_TMR, 3), ENTRY(CORE_PERIPH_UART, 4), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0), ENTRY(CORE_PERIPH_RESERVED, 0) }}, //5.4

};



int _hwpl_core_set_pinsel_func(int gpio_port, int pin, core_periph_t function, int periph_port){
	int i;
	pinsel_table_t pin_cfg;
	int value;
	int iocon_index;
	__IO uint32_t * regs_iocon;

	if( (gpio_port == 5) && (pin > 4) ){
		return -1;
	} else if( pin > 31 ){
		return -1;
	}

	iocon_index = gpio_port * 32 + pin;

	pin_cfg = pinsel_func_table[iocon_index];
	value = -1;
	for(i = 0; i < NUM_ENTRIES; i++){
		if ( (function == ENTRY_GET_FUNCTION(pin_cfg.entry[i])) &&
				(periph_port == ENTRY_GET_PORT(pin_cfg.entry[i])) ){
			//this is a valid pin
			value = i;
			break;
		}
	}

	if ( value < 0 ){
		return -1;
	}

	regs_iocon = (__IO uint32_t *)LPC_IOCON;
	regs_iocon[iocon_index] &= ~0x07;
	regs_iocon[iocon_index] |= value;
	return 0;
}
