/* Copyright 2011; All Rights Reserved
 * Please see http://www.coactionos.com/license.html for
 * licensing information.
 */

#include "hwpl.h"
#include "hwpl/core.h"
#include "hwpl/debug.h"

typedef struct {
	uint8_t entry[4];
} pinsel_table_t;


/*! \brief writes the value of the pin select register.
 * \details This function writes the specified value from 0 to 3 to
 * the corresponding pin select register.
 */
static void core_wr_pinsel(int port /*! The port number for 0 to 4 */,
		int pin /*! The pin number from 0 to 31 */,
		int value /*! The new value from 0 to 3 */){
	HWPL_CLR_MASK( ((uint32_t*)(&(LPC_PINCON->PINSEL0)))[port*2 + pin/16], (3<<(pin < 16 ? pin*2 : ((pin-16)*2) )) );
	HWPL_SET_MASK( ((uint32_t*)(&(LPC_PINCON->PINSEL0)))[port*2 + pin/16], (value<<(pin < 16 ? pin*2 : ((pin-16)*2)) ) );
}


#define PIN(port, pin) (pin | (port<<5))
#define GET_PORT(entry) ((entry>>5) & (0x07)) //shift and get only bottom three bits
#define GET_PIN(entry) (entry&~0xE0)  //clear the top three bits

#define ENTRY(function, port) (port<<5|function)
#define ENTRY_GET_FUNCTION(entry) (entry&~0xE0)
#define ENTRY_GET_PORT(entry) ((entry>>5)&0x07)

#define TOTAL_PINS 71

const uint8_t pinsel_lookup_table[TOTAL_PINS] = {
		PIN(0,0), PIN(0,1), PIN(0,2), PIN(0,3), PIN(0,4), PIN(0,5), PIN(0,6), PIN(0,7),
		PIN(0,8), PIN(0,9), PIN(0,10), PIN(0,11), PIN(0,15),
		PIN(0,16), PIN(0,17), PIN(0,18), PIN(0,19), PIN(0,20), PIN(0,21), PIN(0,22), PIN(0,23),
		PIN(0,24), PIN(0,25), PIN(0,26), PIN(0,27), PIN(0,28), PIN(0,29), PIN(0,30),

		PIN(1,0), PIN(1,1), PIN(1,4),
		PIN(1,8), PIN(1,9), PIN(1,10), PIN(1,14), PIN(1,15),
		PIN(1,16), PIN(1,17), PIN(1,18), PIN(1,19), PIN(1,20), PIN(1,21), PIN(1,22), PIN(1,23),
		PIN(1,24), PIN(1,25), PIN(1,26), PIN(1,27), PIN(1,28), PIN(1,29), PIN(1,30), PIN(1,31),

		PIN(2,0), PIN(2,1), PIN(2,2), PIN(2,3), PIN(2,4), PIN(2,5), PIN(2,6), PIN(2,7),
		PIN(2,8), PIN(2,9), PIN(2,10), PIN(2,11), PIN(2,12), PIN(2,13),

		PIN(3,25), PIN(3,26), PIN(4,28), PIN(4,29)
};

const pinsel_table_t pinsel_func_table[TOTAL_PINS] = {
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_CAN, 1),  ENTRY(CORE_PERIPH_UART, 3),  ENTRY(CORE_PERIPH_I2C, 1) }}, //0.0
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_CAN, 1),  ENTRY(CORE_PERIPH_UART, 3),  ENTRY(CORE_PERIPH_I2C, 1) }}, //0.1
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 0),  ENTRY(CORE_PERIPH_ADC, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.2
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 0),  ENTRY(CORE_PERIPH_ADC, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.3
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_CAN, 2),  ENTRY(CORE_PERIPH_TMR, 2) }}, //0.4
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_CAN, 2),  ENTRY(CORE_PERIPH_TMR, 2) }}, //0.5
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_SPI, 1),  ENTRY(CORE_PERIPH_TMR, 2) }}, //0.6
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_SPI, 1),  ENTRY(CORE_PERIPH_TMR, 2) }}, //0.7
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_SPI, 1),  ENTRY(CORE_PERIPH_TMR, 2) }}, //0.8
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_SPI, 1),  ENTRY(CORE_PERIPH_TMR, 2) }}, //0.9
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 2),  ENTRY(CORE_PERIPH_I2C, 2),  ENTRY(CORE_PERIPH_TMR, 3) }}, //0.10
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 2),  ENTRY(CORE_PERIPH_I2C, 2),  ENTRY(CORE_PERIPH_TMR, 3) }}, //0.11
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_SPI, 0),  ENTRY(CORE_PERIPH_SPI, 2) }}, //0.15
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_SPI, 0),  ENTRY(CORE_PERIPH_SPI, 2) }}, //0.16
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_SPI, 0),  ENTRY(CORE_PERIPH_SPI, 2) }}, //0.17
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_SPI, 0),  ENTRY(CORE_PERIPH_SPI, 2) }}, //0.18
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_I2C, 1) }}, //0.19
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_I2C, 1) }}, //0.20
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_CAN, 1) }}, //0.21
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_CAN, 1) }}, //0.22
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_ADC, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_TMR, 3) }}, //0.23
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_ADC, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_TMR, 3) }}, //0.24
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_ADC, 0),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_UART, 3) }}, //0.25
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_ADC, 0),  ENTRY(CORE_PERIPH_DAC, 0),  ENTRY(CORE_PERIPH_UART, 3) }}, //0.26
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2C, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.27
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_I2C, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.28
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.29
		{{ ENTRY(CORE_PERIPH_GPIO, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //0.30 -- 28

		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.0
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.1
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.4
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.8
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.9
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.10
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.14
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.15
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.16
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_ENET, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //1.17
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_TMR, 1) }}, //1.18
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_PWM, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_TMR, 1) }}, //1.19
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_QEI, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_SPI, 0) }}, //1.20
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_PWM, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_SPI, 0) }}, //1.21
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_PWM, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_TMR, 1) }}, //1.22
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_QEI, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_SPI, 0) }}, //1.23
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_QEI, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_SPI, 0) }}, //1.24
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_PWM, 0),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_TMR, 1) }}, //1.25
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_PWM, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_TMR, 0) }}, //1.26
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_CORE, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_TMR, 0) }}, //1.27
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_PWM, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_TMR, 0) }}, //1.28
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_PWM, 0),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_TMR, 0) }}, //1.29
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_ADC, 0) }}, //1.30
		{{ ENTRY(CORE_PERIPH_GPIO, 1),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_SPI, 1),  ENTRY(CORE_PERIPH_ADC, 0) }}, //1.31 --26

		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.0
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.1
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.2
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.3
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.4
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.5
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_PWM, 1),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.6
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_CAN, 2),  ENTRY(CORE_PERIPH_UART, 1),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.7
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_CAN, 2),  ENTRY(CORE_PERIPH_UART, 2),  ENTRY(CORE_PERIPH_ENET, 1) }}, //2.8
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_USB, 0),  ENTRY(CORE_PERIPH_UART, 2),  ENTRY(CORE_PERIPH_ENET, 1) }}, //2.9
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_EINT, 0),  ENTRY(CORE_PERIPH_CORE, 0),  ENTRY(CORE_PERIPH_RESERVED, 0) }}, //2.10
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_EINT, 1),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_I2S, 0) }}, //2.11
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_EINT, 2),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_I2S, 0) }}, //2.12
		{{ ENTRY(CORE_PERIPH_GPIO, 2),  ENTRY(CORE_PERIPH_EINT, 3),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_I2S, 0) }}, //2.13 -- 14

		{{ ENTRY(CORE_PERIPH_GPIO, 3),  ENTRY(CORE_PERIPH_RESERVED, 0),  ENTRY(CORE_PERIPH_TMR, 0),  ENTRY(CORE_PERIPH_PWM, 1) }}, //3.25
		{{ ENTRY(CORE_PERIPH_GPIO, 3),  ENTRY(CORE_PERIPH_CORE, 0),  ENTRY(CORE_PERIPH_TMR, 0),  ENTRY(CORE_PERIPH_PWM, 1) }}, //3.26
		{{ ENTRY(CORE_PERIPH_GPIO, 4),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_TMR, 2),  ENTRY(CORE_PERIPH_UART, 3) }}, //4.28
		{{ ENTRY(CORE_PERIPH_GPIO, 4),  ENTRY(CORE_PERIPH_I2S, 0),  ENTRY(CORE_PERIPH_TMR, 2),  ENTRY(CORE_PERIPH_UART, 3) }} //4.29 -- 4
};


int _hwpl_core_set_pinsel_func(int gpio_port, int pin, core_periph_t function, int periph_port){
	int i;
	int tmp;
	pinsel_table_t entry;
	int value = -1;
	for(i = 0; i < TOTAL_PINS; i++){
		tmp = pinsel_lookup_table[i];
		if ( (gpio_port == GET_PORT(tmp)) && (pin == GET_PIN(tmp)) ){
			//this is a valid pin
			value = i;
			break;
		}
	}

	if ( value < 0 ){
		return -1;
	}

	entry = pinsel_func_table[value];
	value = -1;
	for(i = 0; i < 4; i++){
		if ( (function == ENTRY_GET_FUNCTION(entry.entry[i])) &&
				(periph_port == ENTRY_GET_PORT(entry.entry[i])) ){
			//this is a valid pin
			value = i;
			break;
		}
	}
	if ( value < 0 ){
		return -1;
	}
	core_wr_pinsel(gpio_port, pin, value);
	return 0;
}

